stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle build --info
  tags:
    - java
    - gradle

deploy_test:
  stage: deploy
  script:
    - gradle publishToTest
  environment:
    name: Test
    url: http://477-33.csse.rose-hulman.edu:8080
  tags:
    - java
    - gradle

deploy_prod:
  stage: deploy
  script:
    - gradle publishToProd
    - gradle publish
  tags:
    - java
    - gradle
  environment:
    name: Prod
    url: http://477-38.csse.rose-hulman.edu:8080
  only:
    - tags