/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CJ' at '1/18/17 8:10 PM' with Gradle 3.0
 *
 * @author CJ, @date 1/18/17 8:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
